import { HttpClient } from '@angular/common/http';
import { Component, Input, OnInit } from '@angular/core';
import { FormBuilder, FormControl } from '@angular/forms';
import { catchError, of } from 'rxjs';
import { ServicesService } from '../Services/services.service';

@Component({
  selector: 'app-hide-show-colm',
  templateUrl: './hide-show-colm.component.html',
  styleUrls: ['./hide-show-colm.component.css'],

})

export class HideShowColmComponent implements OnInit {

  // all: boolean = false;

  // teamRequestId: boolean = true;
  // positionId: boolean = true;
  // positionName: boolean = true;
  // teamRequestName: boolean = true;
  // localGrade: boolean = true;
  // globalGrade: boolean = true;
  // subSector: boolean = true;
  // microSector: boolean = true;
  // source: boolean = false;
  // demandStatus: boolean = false;
  // recruitingId: boolean = false;
  // bUOfAccount: boolean = false;
  // client: boolean = false;
  // demandType: boolean = false;
  // projectCode: boolean = false;
  // jobName: boolean = false;
  // roleNotes: boolean = false;
  // roleType: boolean = false;
  // backFillReason: boolean = false;
  // outgoingEmployee: boolean = false;
  // roleStartDate: boolean = false;
  // roleEndDate: boolean = false;
  // fulfillmentChannelFinal: boolean = false;
  // demandFulfillmentStatus: boolean = false;
  // additionalNotes: boolean = false;
  // bUOfSkill: boolean = false;
  // practice: boolean = false;
  // globalPractice: boolean = false;
  // fte: boolean = false;
  // countryOfDeliveryPrimary: boolean = false;
  // creationDate: boolean = false;
  // updatedOn: boolean = false;
  // weekByStatus: boolean = false;
  // leadtimeInDays: boolean = false;
  // ageing: boolean = false;
  // requestUpdater: boolean = false;
  // teamRequestComment2: boolean = false;
  // buspHandler: boolean = false;
  // pspHandler: boolean = false;
  // recruiter: boolean = false;
  // deliveryRole: boolean = false;
  // deliverySkills: boolean = false;
  // requestedBy: boolean = false;
  // clientReference: boolean = false;
  // expectedDailyRate: boolean = false;
  // roleComment1: boolean = false;
  // deliveryType: boolean = false;
  // primaryLocationName: boolean = false;
  // locationDescription: boolean = false;
  // primaryCity: boolean = false;
  // primaryState: boolean = false;
  // primaryZipCode: boolean = false;
  // primaryRegion: boolean = false;
  // primaryGeoName: boolean = false;
  // primaryGeoCity: boolean = false;
  // closestGeoHub: boolean = false;
  // hubSpoke: boolean = false;
  // productionUnit: boolean = false;
  // productionUnitName: boolean = false;
  // targetBillRate: boolean = false;
  // sellingBU: boolean = false;
  // taleoLocationRequisitionLocation: boolean = false;
  // taleoLocationDemandGeo: boolean = false;
  // taleoLocationClientLocation: boolean = false;
  // accountRegion: boolean = false;
  // accountGeoName: boolean = false;
  // accountGeoCity: boolean = false;
  // thorStage: boolean = false;
  // headCountType: boolean = false;
  // s2rManaged: boolean = false;
  // dmdCaseStatus: boolean = false;
  // taskLabel: boolean = false;
  // s2rId: boolean = false;
  // s2rCaseId: boolean = false;
  // candidateCount: boolean = false;
  // assignedTo: boolean = false;
  // teamRequestStatus: boolean = false;
  // thorOptyId: boolean = false;
  // thorContractType: boolean = false;
  // thorProbability: boolean = false;
  // thorCloseDate: boolean = false;
  // thorStartDate: boolean = false;
  // marketUnitBU: boolean = false;
  // requestCreator: boolean = false;
  // leadMarketArea: boolean = false;
  // leadPracticeArea: boolean = false;
  // sourceOfDemand: boolean = false;
  // agedPastDueYN: boolean = false;
  // weekByStatusGrouped: boolean = false;
  // durationInAgedPastStatus: boolean = false;
  // visible: boolean = false;
  // isClientInterviewRequired: boolean = false;
  // excludeOffshoreDcxID: boolean = false;
  // leadMarketAndPracticeAreaSame: boolean = false;
  // forecastType: boolean = false;
  // daysSincePastDue: boolean = false;
  // noOfSelfAppliedApplications: boolean = false;


    ngOnInit(): void {
        throw new Error('Method not implemented.');

    }

  //   onSelect() {
  //     if (this.all == true) {
  //       this.teamRequestId = true;
  //       this.positionId = true;
  //       this.positionName = true;
  //       this.teamRequestName = true;
  //       this.localGrade = true;
  //       this.globalGrade = true;
  //       this.subSector = true;
  //       this.microSector = true;
  //       this.source = true;
  //       this.demandStatus = true;
  //       this.recruitingId = true;
  //       this.bUOfAccount = true;
  //       this.client = true;
  //       this.demandType = true;
  //       this.projectCode = true;
  //       this.jobName = true;
  //       this.roleNotes = true;
  //       this.roleType = true;
  //       this.backFillReason = true;
  //       this.outgoingEmployee = true;
  //       this.roleStartDate = true;
  //       this.roleEndDate = true;
  //       this.fulfillmentChannelFinal = true;
  //       this.demandFulfillmentStatus = true;
  //       this.additionalNotes = true;
  //       this.bUOfSkill = true;
  //       this.practice = true;
  //       this.globalPractice = true;
  //       this.fte = true;
  //       this.countryOfDeliveryPrimary = true;
  //       this.creationDate = true;
  //       this.updatedOn = true;
  //       this.weekByStatus = true;
  //       this.leadtimeInDays = true;
  //       this.ageing = true;
  //       this.requestUpdater = true;
  //       this.teamRequestComment2 = true;
  //       this.buspHandler = true;
  //       this.pspHandler = true;
  //       this.recruiter = true;
  //       this.deliveryRole = true;
  //       this.deliverySkills = true;
  //       this.requestedBy = true;
  //       this.clientReference = true;
  //       this.expectedDailyRate = true;
  //       this.roleComment1 = true;
  //       this.deliveryType = true;
  //       this.primaryLocationName = true;
  //       this.locationDescription = true;
  //       this.primaryCity = true;
  //       this.primaryState = true;
  //       this.primaryZipCode = true;
  //       this.primaryRegion = true;
  //       this.primaryGeoName = true;
  //       this.primaryGeoCity = true;
  //       this.closestGeoHub = true;
  //       this.hubSpoke = true;
  //       this.productionUnit = true;
  //       this.productionUnitName = true;
  //       this.targetBillRate = true;
  //       this.sellingBU = true;
  //       this.taleoLocationRequisitionLocation = true;
  //       this.taleoLocationDemandGeo = true;
  //       this.taleoLocationClientLocation = true;
  //       this.accountRegion = true;
  //       this.accountGeoName = true;
  //       this.accountGeoCity = true;
  //       this.thorStage = true;
  //       this.headCountType = true;
  //       this.s2rManaged = true;
  //       this.dmdCaseStatus = true;
  //       this.taskLabel = true;
  //       this.s2rId = true;
  //       this.s2rCaseId = true;
  //       this.candidateCount = true;
  //       this.assignedTo = true;
  //       this.teamRequestStatus = true;
  //       this.thorOptyId = true;
  //       this.thorContractType = true;
  //       this.thorProbability = true;
  //       this.thorCloseDate = true;
  //       this.thorStartDate = true;
  //       this.marketUnitBU = true;
  //       this.requestCreator = true;
  //       this.leadMarketArea = true;
  //       this.leadPracticeArea = true;
  //       this.sourceOfDemand = true;
  //       this.agedPastDueYN = true;
  //       this.weekByStatusGrouped = true;
  //       this.durationInAgedPastStatus = true;
  //       this.visible = true;
  //       this.isClientInterviewRequired = true;
  //       this.excludeOffshoreDcxID = true;
  //       this.leadMarketAndPracticeAreaSame = true;
  //       this.forecastType = true;
  //       this.daysSincePastDue = true;
  //       this.noOfSelfAppliedApplications = true;
  //     }
  //     else {
  //       this.teamRequestId= true;
  //       this.positionId = true;
  //       this.positionName = true;
  //       this.teamRequestName = true;
  //       this.localGrade= true;
  //       this.globalGrade= true;
  //       this.subSector= true;
  //       this.microSector = true;
  //       this.source = false;
  //       this.demandStatus = false;
  //       this.recruitingId = false;
  //       this.bUOfAccount = false;
  //       this.client = false;
  //       this.demandType = false;
  //       this.projectCode = false;
  //       this.jobName = false;
  //       this.roleNotes = false;
  //       this.roleType= false;
  //       this.backFillReason= false;
  //       this.outgoingEmployee = false;
  //       this.roleStartDate= false;
  //       this.roleEndDate= false;
  //       this.fulfillmentChannelFinal = false;
  //       this.demandFulfillmentStatus = false;
  //       this.additionalNotes= false;
  //       this.bUOfSkill= false;
  //       this.practice = false;
  //       this.globalPractice= false;
  //       this.fte = false;
  //       this.countryOfDeliveryPrimary= false;
  //       this.creationDate = false;
  //       this.updatedOn = false;
  //       this.weekByStatus= false;
  //       this.leadtimeInDays = false;
  //       this.ageing = false;
  //       this.requestUpdater= false;
  //       this.teamRequestComment2= false;
  //       this.buspHandler= false;
  //       this.pspHandler = false;
  //       this.recruiter= false;
  //       this.deliveryRole = false;
  //       this.deliverySkills= false;
  //       this.requestedBy= false;
  //       this.clientReference= false;
  //       this.expectedDailyRate = false;
  //       this.roleComment1 = false;
  //       this.deliveryType= false;
  //       this.primaryLocationName = false;
  //       this.locationDescription= false;
  //       this.primaryCity= false;
  //       this.primaryState = false;
  //       this.primaryZipCode = false;
  //       this.primaryRegion = false;
  //       this.primaryGeoName= false;
  //       this.primaryGeoCity = false;
  //       this.closestGeoHub = false;
  //       this.hubSpoke= false;
  //       this.productionUnit = false;
  //       this.productionUnitName= false;
  //       this.targetBillRate= false;
  //       this.sellingBU= false;
  //       this.taleoLocationRequisitionLocation = false;
  //       this.taleoLocationDemandGeo= false;
  //       this.taleoLocationClientLocation= false;
  //       this.accountRegion= false;
  //       this.accountGeoName= false;
  //       this.accountGeoCity= false;
  //       this.thorStage= false;
  //       this.headCountType = false;
  //       this.s2rManaged= false;
  //       this.dmdCaseStatus= false;
  //       this.taskLabel = false;
  //       this.s2rId = false;
  //       this.s2rCaseId = false;
  //       this.candidateCount= false;
  //       this.assignedTo= false;
  //       this.teamRequestStatus = false;
  //       this.thorOptyId= false;
  //       this.thorContractType = false;
  //       this.thorProbability = false;
  //       this.thorCloseDate = false;
  //       this.thorStartDate = false;
  //       this.marketUnitBU= false;
  //       this.requestCreator = false;
  //       this.leadMarketArea = false;
  //       this.leadPracticeArea = false;
  //       this.sourceOfDemand= false;
  //       this.agedPastDueYN= false;
  //       this.weekByStatusGrouped = false;
  //       this.durationInAgedPastStatus = false;
  //       this.visible= false;
  //       this.isClientInterviewRequired = false;
  //       this.excludeOffshoreDcxID= false;
  //       this.leadMarketAndPracticeAreaSame = false;
  //       this.forecastType = false;
  //       this.daysSincePastDue = false;
  //       this.noOfSelfAppliedApplications = false;
  //     }

      
  //   }

}

 


